changelog:
  categories:
    - title: ?? Breaking Changes
      labels:
        - breaking-change # ??? PR, ??????? ?????? ???????? ?????????
    - title: ? New Features
      labels:
        - enhancement     # ??? PR ? ?????? ?????????
    - title: ?? Bug Fixes
      labels:
        - bug             # ??? PR, ??????? ?????????? ??????
    - title: ?? Documentation
      labels:
        - documentation   # ??? PR ? ??????????? ? ????????????
    - title: ?? Chores
      labels:
        - chore           # ??? PR ? ???????? ?????? ?????????, ?????? ??? ?????????? ????????????
    - title: ?? Refactoring
      labels:
        - refactor        # ??? PR, ??????? ???????? ??????????? ???? ??? ????????? ????????????????
    - title: Other Changes
      labels:
        - "*"             # ??? ???? ????????? PR, ??????? ?? ?????? ? ????????????? ?????????