name: Build and Upload Release

on:
  push:
    tags:
      - '*'

jobs:
  build_and_release:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
    
    - name: Publish Release
      run: dotnet publish ./LogReader.Desktop/LogReader.Desktop.csproj -c Release -r win-x64 --no-self-contained --p:PublishSingleFile=true -o publish
    
    - name: Zip the published app
      run: Compress-Archive -Path publish/* -DestinationPath LogReader-${{ github.ref_name }}-Windows-x64.zip
    
    - name: Generate changelog
      id: changelog
      run: |
        echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
        git fetch --tags
        LATEST_TAG=$(git describe --tags --abbrev=0 --tags)
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 --tags $(git rev-list --tags --skip=1 --max-count=1))
        if [ -z "$PREVIOUS_TAG" ]; then
          git log --pretty=format:"- %s" $LATEST_TAG..HEAD >> $GITHUB_ENV
        else
          git log --pretty=format:"- %s" $PREVIOUS_TAG..$LATEST_TAG >> $GITHUB_ENV
        fi
        echo 'EOF' >> $GITHUB_ENV
      shell: bash

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        body: ${{ env.CHANGELOG }}
        asset_path: ./LogReader-${{ github.ref_name }}-Windows-x64.zip
        asset_name: LogReader-${{ github.ref_name }}-Windows-x64.zip
        asset_content_type: application/zip

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./LogReader-${{ github.ref_name }}-Windows-x64.zip
        asset_name: LogReader-${{ github.ref_name }}-Windows-x64.zip
        asset_content_type: application/zip
